DNA = 'TTCTCTGACGCGTGAGATCCAACAAGGCGTTTCAAGATTCGGTTGGCAATTACGAACTTGTGCTCCTCACTTGTCGCACTAGTCCTCTGACACACGATTGACAAGGCCCAACAATGGGAGCCATCGATGCCAGCAGTGATAAAATATGTATGTCGTGCGGACAGTCCCCATAGGGGGTCGCGCGTGGCTCTGCTCTATCGTACTCTGATAAAACTGAATATTAATCAATCTGAGTCATCCTCTTGGCTTCGGAGTAACAGTACCCAATAAGCTGAGTCCGCGAAGGAGGAGTGACAAACGGATCCGAAGATAATCTCCTGCTCACTTCGATTGATTTTAGGGGATTCCTCTGCAACTGCGCTGAAAGGGGTGTGTTTCGCACCCTGTTCATTAGGTCATATCCGTTGGTTCTGGGACAAATGTGCTCTTAACAAAGGAGAAGCATTTTAGTACTGAAATCACCCCCTCATAGAGCCAGGCGCGCTTACTCGATCTCCCCGGAAGTTTGGACTCTATTAGGCTGAACAGTGTGGATGGATCACCTGCGTCCCAGGTATCTGCAGTGATATCGGGTAGGCAACACCCAGCCCGAATGAGATCTGATCATACTTTGGAGGGTCGCACCGTAACTAACCGGCCATGAATGGTCGAAGACCGGGAGGTCCCACTGGACTCCACTCACCTCAGCAGTCACTACATTCAACAATGAAAAGATGGTCCGAATTCCTCTGCGTCACTGGCAGAGAGACCGCGCACTGCCCCGCGGCCTTCTGCCTTGCAGAGCAGGAACTGGCTACTTACAAGCCGAAACCTTCAGCACAACATAATGGATT'


def reverse_complement(str):
	l = []
	for c in DNA:
		if c == "A":
			l.append("T")
		elif c == "C":
			l.append("G")
		elif c == "G":
			l.append("C")
		else: l.append("A")
		
	return ''.join(sorted(l))



print reverse_complement(DNA)
