str="AGCCACCTCTACCGGTCGAAATTCAAGCGATATAAGGGAGTCCGCCGGACTTCAGAGCTGAAACTCGGTATGTGGCAGTGTCGGTTGGCGGAGTCGCTCTGTCTACTGAAATCTGCTTGTATGAACAGTCGAAGGAACCAAGGATGTCGACCCACGATCGTCATAACGCACGGTTTGAAGCGGACGCTAGAAGGAGTCCAAGCAGACTCACAAGTTACCAATTTTGAAAGTCGGTATACTGTGTTTTGTCAGAAATGTCTGCCGCTGGACGACGTGGCCTGGCCTAGATATTAAGGCTATGAGCACAACGAGAATGTGCGCAGCGGGGTACGATAAGTTTCAGTTATACGGACCACCACCCACCGCTACCCACTGGCTAGCTATATCAACTACCGAGCAGCACTATGGCTACTCGTACACTAACCACCGTGCGACAATCGGTAGGGGCTTGACACTTCTTGATCACTTATACTTTAAGTCTTAAAAGCCCATGGTTCATAAGAACGGGAGGGTCATTCTCTGGACTTGGTCTTTTCCCGATCGGATATTAACCAAGGATGGCAACATTCTAATTCTCTCGCCGGTGCGTCGCGAACCTAGCCTGATTAGCAAAAGGGTATCGGCCGACGCCCACGATCTTTTGTCCAGCCAGTCTGGAGATGATGATGCTGTGTTATTACGCTAGTGGGCTCTGTAGTGGCTTTTAACTCCAACCGATGCTAGTAGGCCCGCATAATGGCGCTTAACTTAAGAGAGGTACCTAGAATAGAAGAGAGGGTGGGCTTGACGATCTTATCAAAAAGACTTCGCCGGTGAAATAGATTATTGAACGTCATATG"

d = {}
for c in str:
    if c not in d:
        d[c] = 1
    else:
        d[c] += 1
    
l = []

for v in d:
    s =  v,d[v] 
    l.append(s)

print sorted(l)
