#!/usr/bin/env python

DNA = 'ACGCATACTAGTTGCTAGAGTTGTAGGGTCTGTCCCCCATCCCCGTCCACGCGTCGTGATCCATACCAACGTTCCTAAAGGTAGTGTGGCGCTGGGTTGCGCCACAGGCTATGGCTAACAGGTTCCGGGAATCGTTTATAGAATGCGGGACTGAGGATATATAACGGAAAATCGCATTATTGGCAGTAGAACTTTCCGAATTCTTGCTACTTAATCAAGCTCCTGAGAGAGGTACATGTTGGCGCTACGCGAGACGCATTCGAATACGCGTCGTCCTGTACGCGGTGTCCTGCGAATTCTTGATACACTTAGGGTCCCGCTGGGAGGCCACCTGTTGTCCTATAGCGAGGTGGATAACAAGGGTAAGTCGCGTAGACGACTGGTCGCCGGTCTCACCGCGCTGCGGCGTTGTGATAGAGGACTGTTGGGACTGAAGGAGGTGTGACGACTGGGTACATGATTATAAACTTGCCGGTGCCTGCGGCACGTCATTTTGCGAATGAGTTGGACATACAACGGATCGCAGGTACCAACAGCCGGTCCCCAAATTAGGCAATCTTGCTTTGTAGTATCACTCGGGGGGGTCGTACTAAATATCCGCAGCCTTAAATATTATAAGCACCGCGAGTCGCCGGTAGGGTTTAATTTTCGCTGGACAGCTATGTGCCTCCGACAAGTAAGTGGGACGCTGTAGCGATGCCTCCACAACTATCCATGTTGCCGGGAGTCGTAACTGACTCTTTGCACTTATAGGAATAGTCCATTATGCGCGCGGCAGGACCGGTGTTGTTGTGCTCTTTCCCGATGACGGGCATTAGCAGGCACGACGTTGCTGTACAGCTAAGGCTCAATTATCTAGACGGAGGTGGGTCCGGATACGGACTATCAGAGCATTCGTATCGATGAGGCCACGTATATTTATACTCGAATCGCCCAGGT'

# Solution 1#
#def dna_to_rna(dna):
#	l = []
#	for i in DNA:
#		if i == "T":
#			l.append("U")
#		else:
#			l.append(i)
#	return ''.join(l)
#
#
#print dna_to_rna(DNA)

#---------------------------------

# Solution 2#
print DNA.replace("T","U")

#---------------------------------


